# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-01 18:53
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_tetris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre'),
        ),
    ]
